title: BuzzKill Rubber
email: buzzkill@kaymic.com
description: > # this means to ignore newlines until "baseurl:"
  Helping Demo Drivers keep it on all 4's since 2010.
baseurl: ""
# url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty